export const dogTraining = [
  {
    professionalsToFind: 'Dog Trainers',
    type: 'intro',
    nextButtons: 'next',
  },
  {
    question: 'How many dogs would you like trained?',
    type: 'single',
    options: ['1 dog', '2 dogs'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Which additional services do you need, if any?',
    type: 'single',
    options: [
      '0 - 6 months old',
      '0 - 12 months old',
      '1 - 2 years old',
      '2 - 10 years old',
      '10 years or older',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'What is the size of your dog?',
    type: 'single',
    options: [
      'Extra small(1 - 15 lbs)',
      'Small (16 - 25 lbs)',
      'Medium (26 - 40 lbs)',
      'Large (41 - 70 lbs)',
      'Extra large(70+ lbs)',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Are you looking for private lessons or board and train programs?',
    type: 'single',
    options: ['Private dog training lessons', 'Board and train programs at a facility'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Which of the dog training packages are you interested in?',
    type: 'single',
    options: [
      'Puppy training',
      'Aggressive behavior modification',
      'General obedience training',
      'Therapy or service dog training',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'If you would like the trainer to address any specific issues, please specify below.',
    type: 'multi',
    options: [
      'Leash pulling',
      'House training',
      'Barking',
      'Digging',
      'Biting',
      'Chewing',
      'Destructive behavior',
      'Crate training',
    ],
    required: true,
    nextButtons: 'backAndSkip',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'How would you like to meet with the dog trainer?',
    type: 'single',
    options: ['I travel to the dog trainer', 'The dog trainer travels to me'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'When do you need this service?',
    type: 'multi',
    options: ['Weekday mornings', 'Weekday afternoons', 'Weekday evenings', 'Saturday/Sunday'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Anything else the dog trainer should know?',
    type: 'textarea',
    required: false,
    nextButtons: 'backAndSkip',
    validation: '',
    validationMessage: '',
  },
  {
    question: 'Please confirm where you need the house cleaner.',
    type: 'zipCode',
    required: true,
    nextButtons: 'backAndNext',
    validation: 'zipcode',
    validationMessage: 'Please give a valid 5-digit zipcode.',
  },
  {
    question: 'Where should we send your matches?',
    type: 'email',
    required: true,
    nextButtons: 'backAndNext',
    validation: 'email',
    validationMessage: 'Please give a valid email address.',
  },
  {
    question: 'Please enter your full name.',
    type: 'name',
    required: true,
    nextButtons: 'submit',
    validation: 'name',
    validationMessage: 'Please give your full name.',
  },
];
