export const localMoving = [
  {
    professionalsToFind: 'Movers',
    type: 'intro',
    nextButtons: 'next',
  },
  {
    question: 'What are you moving?',
    type: 'single',
    options: [
      'Studio',
      '1 bedroom home',
      '2 bedroom home',
      '3 bedroom home',
      '4 bedroom home',
      '5 bedroom home',
      'Just a few things',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'What type of property are you moving from?',
    type: 'single',
    options: [
      'Apartment',
      'Condo',
      'One-story house',
      'Two-story house',
      'Townhouse',
      'Storage unit',
      'Other type of property',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'How far are you moving?',
    type: 'single',
    options: [
      'Within the same building',
      'Less than 5 miles',
      '5 - 10 miles',
      '11 - 20 miles',
      '21 - 30 miles',
      '31 - 50 miles',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'In addition to moving, do you need any of the following services?',
    type: 'multi',
    options: [
      'Packing belongings into boxes',
      'Furniture assembly and disassembly',
      'Piano moving',
      'Digging',
      'Pool table moving',
      'Safe or security box moving',
    ],
    required: true,
    nextButtons: 'backAndSkip',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Approximately how many boxes need to be moved?',
    type: 'single',
    options: ['1 - 10 boxes', '11 - 20 boxes', '21 - 40 boxes', '41 - 100 boxes', 'No boxes'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Will the mover need to use stairs at the location you are moving from?',
    type: 'single',
    options: [
      'Yes, the mover will move items up/down stairs',
      'No, the mover has access to a passenger elevator',
      'No, the mover has access to a freight elevator',
      'No, the move is on the ground floor',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Will the mover need to use stairs at the location you are moving to?',
    type: 'single',
    options: [
      'Yes, the mover will move items up/down stairs',
      'No, the mover has access to a passenger elevator',
      'No, the mover has access to a freight elevator',
      'No, the move is on the ground floor',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Where are you in your hiring process?',
    type: 'single',
    options: [
      'Ready to hire the right mover',
      'Need some more information before hiring',
      'Conducting initial research',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Anything else the mover should know?',
    type: 'textarea',
    required: false,
    nextButtons: 'backAndSkip',
    validation: '',
    validationMessage: '',
  },
  {
    question: 'Please confirm where you need the house cleaner.',
    type: 'zipCode',
    required: true,
    nextButtons: 'backAndNext',
    validation: 'zipcode',
    validationMessage: 'Please give a valid 5-digit zipcode.',
  },
  {
    question: 'Where should we send your matches?',
    type: 'email',
    required: true,
    nextButtons: 'backAndNext',
    validation: 'email',
    validationMessage: 'Please give a valid email address.',
  },
  {
    question: 'Please enter your full name.',
    type: 'name',
    required: true,
    nextButtons: 'submit',
    validation: 'name',
    validationMessage: 'Please give your full name.',
  },
];
