export const personalTraining = [
  {
    professionalsToFind: 'Personal Trainers',
    type: 'intro',
    nextButtons: 'next',
  },
  {
    question: 'How many people will attend the training sessions?',
    type: 'single',
    options: ['One person (individual training)', 'Two people (couples training)'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Currently, how often do you exercise?',
    type: 'single',
    options: [
      '0  times per week',
      '1 - 2 times per week',
      '3 - 4  times per week',
      '5 - 7 times per week',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'What is your primary fitness goal?',
    type: 'single',
    options: ['Lose weight', 'Get toned', 'Build muscle', 'Gain flexibility', 'Boost endurance'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Are you preparing for a specific event?',
    type: 'multi',
    options: ['Athletic event or competition', 'Wedding', 'Vacation', 'Other'],
    required: true,
    nextButtons: 'backAndSkip',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question:
      'Are there any injuries or pre-existing medical conditions that the trainer should be aware of?',
    type: 'multi',
    options: ['Asthma', 'Back problems', 'Joint pain', 'Other injuries or medical conditions'],
    required: false,
    nextButtons: 'backAndSkip',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'How old is the client?',
    type: 'single',
    options: [
      'Younger than 18',
      '18 - 22 years old',
      '23 - 30 years old',
      '31 - 40 years old',
      '41 - 50 years old',
      '51 - 60 years old',
      '61 - 70 years old',
      '71 or older',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Do you prefer to work with a trainer of a certain gender?',
    type: 'single',
    options: [
      'I have no preference',
      'I would like female trainers only',
      'I would like male trainers only',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Do you have a preference for a specific training location?',
    type: 'multi',
    options: [
      "Trainer's gym or private studio",
      'Public outdoors location',
      'My home or apartment gym',
      'A location recommended by the trainer',
    ],
    required: true,
    nextButtons: 'backAndSkip',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'When do you need this service?',
    type: 'single',
    options: ['In the next few days', 'Within a week', 'As recommended by the pro'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'How often would you like to meet with the trainer?',
    type: 'single',
    options: ['Once a week', '2-3 times a week', '4 - 7 times a week'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Anything else the personal trainer should know?',
    type: 'textarea',
    required: false,
    nextButtons: 'backAndSkip',
    validation: '',
    validationMessage: '',
  },
  {
    question: 'Please confirm where you need the personal trainer.',
    type: 'zipCode',
    required: true,
    nextButtons: 'backAndNext',
    validation: 'zipcode',
    validationMessage: 'Please give a valid 5-digit zipcode.',
  },
  {
    question: 'Where should we send your matches?',
    type: 'email',
    required: true,
    nextButtons: 'backAndNext',
    validation: 'email',
    validationMessage: 'Please give a valid email address.',
  },
  {
    question: 'Please enter your full name.',
    type: 'name',
    required: true,
    nextButtons: 'submit',
    validation: 'name',
    validationMessage: 'Please give your full name.',
  },
];
