export const questionaire = [
  {
    professionalsToFind: 'House Cleaners',
    type: 'intro',
    nextButtons: 'next',
  },
  {
    question: 'How many bedrooms are in your home?',
    type: 'single',
    options: ['1 bedroom', '2 bedrooms', '3 bedrooms', '4 bedrooms', '5 bedrooms', '6 bedrooms'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'How many bathrooms are in your home?',
    type: 'single',
    options: ['1 bathroom', '2 bathrooms', '3 bathrooms', '4 bathrooms', '5 bathrooms'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'What is the square footage of your home?',
    type: 'single',
    options: [
      'Less than 1,000 sq ft',
      '1,000 - 1,500 sq ft',
      '1,500 - 2,000 sq ft',
      '2,000 - 2,500 sq ft',
      '2,500 - 3,000 sq ft',
      '3,000 - 3,500 sq ft',
      '3,500 - 4,000 sq ft',
      '4,000 - 4,500 sq ft',
      '4,500 - 5,000 sq ft',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'What kind of cleaning service would you like?',
    type: 'single',
    options: ['Standard cleaning', 'Deep cleaning', 'Move out cleaning'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Which additional services do you need, if any?',
    type: 'multi',
    options: ['Fridge cleaning', 'Oven cleaning', 'Interior window cleaning', 'Laundry'],
    required: false,
    nextButtons: 'backAndSkip',
    validation: '',
    validationMessage: '',
  },
  {
    question: 'Are there any cats or dogs in your house?',
    type: 'single',
    options: ['Yes, I have a cat or dog', "No, I don't have a cat or dog"],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'When do you need this service?',
    type: 'single',
    options: ['In the next few days', 'Within a week', 'As recommended by the pro'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Which additional services do you need, if any?',
    type: 'multi',
    options: [
      'Early Morning (before 9am)',
      'Morning (9am - 12pm)',
      'Afternoon (12pm - 3p,m)',
      'Late Afternoon (3pm - ,6pm)',
      'Evening (after 6pm)',
    ],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'How often would you like your house cleaned?',
    type: 'single',
    options: ['Just once', 'Every week', 'Every 2 we,eks', 'Once a month'],
    required: true,
    nextButtons: 'backAndNext',
    validation: 'required',
    validationMessage: 'Please give an answer',
  },
  {
    question: 'Anything else the house cleaner should know?',
    type: 'textarea',
    required: false,
    nextButtons: 'backAndSkip',
    validation: '',
    validationMessage: '',
  },
  {
    question: 'Please confirm where you need the house cleaner.',
    type: 'zipCode',
    required: true,
    nextButtons: 'backAndNext',
    validation: 'zipcode',
    validationMessage: 'Please give a valid 5-digit zipcode.',
  },
  {
    question: 'Where should we send your matches?',
    type: 'email',
    required: true,
    nextButtons: 'backAndNext',
    validation: 'email',
    validationMessage: 'Please give a valid email address.',
  },
  {
    question: 'Please enter your full name.',
    type: 'name',
    required: true,
    nextButtons: 'submit',
    validation: 'name',
    validationMessage: 'Please give your full name.',
  },
];
